# Generated by Django 5.2.1 on 2025-06-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыт'),
        ),
    ]
